[tool.poetry]
name = "web_file_downloader"
version = "0.1.4"
description = "Download web hosted files by filetype/file extension."
authors = ["Mitch Haddadi <12067255+dfirsec@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "web_file_downloader"}]

[tool.poetry.dependencies]
python = "^3.10"
aiofiles = "^23.2.1"
aiohttp = "^3.8.5"
async-timeout = "^4.0.2"
beautifulsoup4 = "^4.11.1"
requests = "^2.31.0"
rich = "^13.7.0"
lxml = "^5.0.0"
fake-useragent = "^1.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
