[tool.poetry]
name = "web-dl-by-type"
version = "0.1.0"
description = "Download web hosted files by filetype/file extension."
authors = ["Mitch Haddadi <12067255+dfirsec@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "web_dl_by_type"}]

[tool.poetry.dependencies]
python = "^3.11"
aiofiles = "^22.1.0"
aiohttp = "^3.8.5"
async-timeout = "^4.0.2"
beautifulsoup4 = "^4.11.1"
requests = "^2.31.0"
rich = "^12.6.0"
lxml = "^4.9.2"
fake-useragent = "^1.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
